# Please NOTE that the admin JS package is missing, since we're going to re-do the UI for it entirely... someday.
# NOTE concept-manager is a little weird, since it's in V1 layout still. It should be revisited.
---
javascripts:
- application:
  - jquery-1.6.1.min
  - rails
  - application
  - jquery.cycle.all.min
  - jquery.modal
  - comments
- errors:
  - jquery-1.6.1.min
  - rails
  - application
- data-object-curation:
  - curation
- new-text:
  - curation
  - new-text
- data-object-show:
  - jplayer/js/jquery.jplayer.min
  - permalink
- concept-manager:
  - jquery
  - jquery_ui
  - concept_manager
- collections:
  - collections
- communities:
  - communities
- mobile:
  - jquery-1.6.1.min
  - jquery.mobile-1.0b1.min
  - mobile
  - touch-gallery/activity-indicator
  - touch-gallery/transform
  - touch-gallery/touch-gallery
- new-community:
  - communities
  - jquery.spotlite
- taxa-navigation:
  - navigation
- maps:
  - swfobject
- taxa-media:
  - exemplar_image
- taxa-media-footer:
  - jplayer/js/jquery.jplayer.min
  - media_list
- common-names:
  - common-names
- worklist:
  - permalink
  - worklist
  - jplayer/js/jquery.jplayer.min

stylesheets:
- application:
  - application
  - accessibility
- admin:
  - application
  - accessibility
- home:
  - home
  - accessibility
- ie7:
  - ie7
- errors:
  - errors
  - accessibility
- v1:
  - reset-min
  - main
  - popup
  - taxa_comments
  - tags
  - star_rating
  - wikipedia
- buttons:
  - buttons
- api:
  - api
- content-preview:
  - home
  - accessibility
- mobile:
  - jquery.mobile-1.0b1.min
  - mobile
